name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: lc0
      run: cargo make 0
    - name: lc100
      run: cargo make 100
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
